config/routes.rb
ProjectOctober::Application.routes.draw do

  devise_for :users, :path => 'auth', :controllers => {
    :registrations => 'users',
    :sessions => 'home',
  }
  devise_scope :user do
    resources :users, :only => :show do
      resources :subscriptions, :only => [:create, :destroy]

      member do
        get 'follow'
        get 'unfollow'
        get 'keywords'
        resource :keywords, :only => [:create, :destroy], :controller => 'user_keywords'
      end
    end

    resources :feeds, :only => :show, :controller => 'users' do
      member do
        get 'follow'
        get 'unfollow'
      end
    end

    resources :posts, :id => /\d+/ do
      member do
        get 'upvote'
        get 'downvote'
        get 'debug'
        resources :comments
      end
      collection do
        post 'fetch'
        get 'recommendations'
      end
    end
  end

  devise_scope :user do
    root :to => 'home#index'
    get '/about' => 'home#about'
    match '/404', :to => 'errors#error_404'
    match '/500', :to => 'errors#error_500'
  end

end

app/models/user.rb
# encoding: UTF-8

class User < Poster
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :subscriptions
  has_many :feeds, :through => :subscriptions
  has_many :votes
  has_many :comments

  after_create :backend_register

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me

  validates :name, :length => {:minimum => 3,
    :maximum => 25,
    :too_short => "Usernames must have at least %{count} characters",
    :too_long => "Usernames cannot have less than %{count} characters"}
  validates :name, :uniqueness => {:message => "This username already exists"}
  validate :name_cannot_have_whitespace
  validate :name_cannot_have_special_chars

  def vote(post, direction=Vote.UP)
    vote = post.votes.where(:user_id => id, :post_id => post.id).first_or_initialize
    vote.direction = direction
    if vote.save
      # TODO: add undo directions here
      if direction == Vote.UP
        THRIFTCLIENT.userToPost(id, Backend::Action::VOTE_UP, post.id)
      else
        THRIFTCLIENT.userToPost(id, Backend::Action::VOTE_DOWN, post.id)
      end
    end
  end

  def top_keywords(n = 10)
    THRIFTCLIENT.userTopTerms(id, n).sort_by { |_, v| v }.reverse
  end

  def add_keywords(ary)
    return THRIFTCLIENT.addUserTerms(id, ary)
  end

  def remove_keywords(ary)
    return THRIFTCLIENT.removeUserTerms(id, ary)
  end

  def needs_onboarding?
    THRIFTCLIENT.userTopTerms(id, 1).empty?
  end

  def can_follow?(other)
    return false if id == other.id
    return false if followings.pluck(:following_id).include?(other.id)

    true
  end

  def subscribe_to_feed(url)
    feed = Feed.where(:url => url).first_or_create
    return false unless feed.present?
    subscription = subscriptions.where(:feed_id => feed.id).first_or_create
    subscription.persisted?
  end

  class << self
    def search(query)
      terms = query.split(' ').first(10)
      results = Hash.new(0)
      terms.each do |t|
        User.where('name LIKE ?', "%#{t}%").limit(30).each do |u|
          results[u] = results[u] + 1
        end
      end
      results.sort_by { |_, v| v }.reverse.map(&:first)
    end
  end

  private
    def name_cannot_have_whitespace
      if name.present? && name.match(/\s/)
        errors[:username] << "cannot have spaces in it"
      end
    end

    def name_cannot_have_special_chars
      if name.present? && name.match(/[^\w-]/)
        errors[:username] << "cannot have special characters in it"
      end
    end

    def backend_register
      THRIFTCLIENT.addUser(self.id)
    end
end

app/controllers/users_controller.rb
class UsersController < Devise::RegistrationsController
  before_filter :authenticate_user!
  layout "splash", :only => :new

  def show
    if request.fullpath.match(/\A\/feed/)
      @user = Feed.find(params[:id])
    else
      @user = User.where(:name => params[:id]).includes(:posts).first
    end

    return redirect_to root_path, :flash => { :error => "Unknown User!" } unless @user.present?
  end

  def follow
    @user = Poster.find(params[:id])

    if current_user.followings.create(:following_id => @user.id)
      flash[:notice] = "Now following #{@user.name}"
    end

    redirect_to feed_path(@user.id) if @user.is_a?(Feed)
    redirect_to user_path(@user.name) if @user.is_a?(User)
  end

  def unfollow
    @user = Poster.find(params[:id])

    if current_user.followings.where(:following_id => @user.id).delete_all
      flash[:notice] = "Stopped following #{@user.name}"
    end

    redirect_to feed_path(@user.id) if @user.is_a?(Feed)
    redirect_to user_path(@user.name) if @user.is_a?(User)
  end

  def keywords
    @user = User.where(:name => params[:id]).first
    @keywords = @user.top_keywords(20)
  end

  # From Devise:
  # POST /resource
  def create
    build_resource

    if resource.save
      if resource.active_for_authentication?
        set_flash_message :notice, :signed_up if is_navigational_format?
        sign_up(resource_name, resource)
        UserMailer.welcome_email(resource).deliver
        respond_with resource, :location => after_sign_up_path_for(resource)
      else
        set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_navigational_format?
        expire_session_data_after_sign_in!
        respond_with resource, :location => after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      flash[:error] = resource.errors.full_messages.first
      redirect_to new_user_registration_path
    end
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/_avatar_box.html.haml
.span3.box
  .avatar
    - if user.is_a?(Feed)
      %i.icon-rss{ :style => 'color: #ccc; font-size: 128px;' }
    - else
      = image_tag gravatar_url(user), :width => '128', :height => '128'
    %h2 #{user.name}
  - if current_user.id == user.id
    = link_to 'Manage Your Account', edit_user_registration_path, :class => 'btn btn-primary'
    = link_to 'View/Modify Keywords', keywords_user_path, :class => 'btn'
  - else
    - if current_user.can_follow?(user)
      = link_to 'Follow Me', follow_user_path(user.id), :class => 'btn'
    - else
      = link_to 'Followed!', unfollow_user_path(user.id), :class => 'btn btn-primary'

app/views/users/edit.html.haml
.row
  .span5
    %h2 Edit #{resource_name.to_s.humanize} #{resource.name}
    = form_for(resource, :as => resource_name, :url => registration_path(resource_name), :html => { :method => :put, :class => 'form-horizontal'}) do |f|
      = devise_error_messages!

      .control-group
        = f.label :email, :class => 'control-label'
        .controls
          = f.email_field :email, :autofocus => true

      - if devise_mapping.confirmable? && resource.pending_reconfirmation?
        %div
          Currently waiting confirmation for:
          = resource.unconfirmed_email

      .control-group
        = f.label :password, :class => 'control-label'
        .controls
          = f.password_field :password, :autocomplete => "off"
          %br
          %i (leave blank if you don't want to change it)

      .control-group
        = f.label :password_confirmation, :class => 'control-label'
        .controls
          = f.password_field :password_confirmation

      .control-group
        = f.label :current_password, :class => 'control-label'
        .controls
          = f.password_field :current_password
          %br
          %i (we need your current password to confirm your changes)

      .form-actions
        = f.submit "Update", :class => 'btn btn-primary'
        = link_to "Back", :back, :class => 'btn'
  .span5.offset1
    %h3 My Subscriptions
    %ul
      - resource.subscriptions.each do |s|
        %li
          %p
            = s.feed.name
            = link_to '[x]', user_subscription_path(resource.id, s.id), :method => :delete
    = form_for Feed.new, :url => user_subscriptions_path(resource.id), :html => { :class => 'form-inline' } do |f|
      =f.text_field :url, :class => 'input-large', :placeholder => 'RSS Feed URL'
      =f.submit 'Subscribe', :class => 'btn btn-primary'
    %h3 Cancel my account
    %p
      Unhappy?
      = button_to "Cancel my account", registration_path(resource_name), :data => { :confirm => "Are you sure?" }, :method => :delete

app/views/users/keywords.html.haml
- content_for :javascripts do
  = javascript_include_tag 'tag-it.min'
  :javascript
    $(function() {
      $("#more_keywords").tagit({ fieldName: 'tags[]', allowSpaces: true});
    });
- content_for :stylesheets do
  = stylesheet_link_tag 'tag-it'
.row
  .span8
    - if current_user == @user
      .box
        %h2 suggest more keywords for yourself:
        = form_for('onboard', :url => keywords_path(current_user)) do |f|
          %ul#more_keywords
          %span.help-block separate keywords with commas
          = f.submit 'Add Keywords!', :class => 'btn btn-primary'
    %h2 top keywords
    %p Click the [x] next to a keyword to no longer receive recommendations based on that keyword.
    %ol
      - @keywords.each do |k|
        %li
          %p{ :title => "Weight: #{k[1]}" }
            #{k[0]} #{link_to '[x]', keywords_path(@user.id, :tags => k[0]), :method => :delete}
    %h2 clear all my keywords
    %p This will remove our most powerful recommendation signals for you. This cannot be undone.
    = link_to 'Clear Top 20 Keywords', keywords_path(@user.id, :tags => @keywords.map(&:first).join(',')), :method => :delete, :class => 'btn'
    %p
      &nbsp;
  = render 'avatar_box', :user => @user

app/views/users/new.html.haml
- content_for :javascripts do
  :javascript
    $(function() {
      mixpanel.track_forms("#new_user", "User Registration Attempt");
    });
.span5
  %h2 Sign Up
  = form_for(resource, :as => resource_name, :url => registration_path(resource_name), :html => { :class => 'form-horizontal' }) do |f|
    = devise_error_messages!

    .control-group
      = f.label :name, 'Username', :class => 'control-label'
      .controls
        = f.text_field :name, :autofocus => true, :class => 'span3'

    .control-group
      = f.label :email, :class => 'control-label'
      .controls
        = f.email_field :email, :class => 'span3'

    .control-group
      = f.label :password, :class => 'control-label'
      .controls
        = f.password_field :password, :class => 'span3'

    .control-group
      = f.label :password_confirmation, :class => 'control-label'
      .controls
        = f.password_field :password_confirmation, :class => 'span3'

    .control-group
      .controls
        .btn-group
          = f.submit 'Create Account', :class => 'btn btn-primary'
          = link_to 'Cancel', new_user_session_path, :class => 'btn'
          = render 'devise/shared/links'
.span5.offset1
  %h2 You're just about there...
  %p
    In
    %b just a few moments
    you will be reading only the news you want to read.

app/views/users/show.html.haml
.row
  .span8
    %h2 posts
    %ul
      - @user.posts.each do |p|
        %li
          %p= link_to p.title, post_url(p)
    %h2 comments
    %ul
      - @user.comments.each do |c|
        %li
          %p
            = link_to c.body, post_url(c.post_id)
            %span{:style => 'font-size: 0.6em'} #{distance_of_time_in_words(c.created_at, Time.now)} ago


  = render 'avatar_box', :user => @user