config/routes.rb
ProjectOctober::Application.routes.draw do

  devise_for :users, :path => 'auth', :controllers => {
    :registrations => 'users',
    :sessions => 'home',
  }
  devise_scope :user do
    resources :users, :only => :show do
      resources :subscriptions, :only => [:create, :destroy]

      member do
        get 'follow'
        get 'unfollow'
        get 'keywords'
        resource :keywords, :only => [:create, :destroy], :controller => 'user_keywords'
      end
    end

    resources :feeds, :only => :show, :controller => 'users' do
      member do
        get 'follow'
        get 'unfollow'
      end
    end

    resources :posts, :id => /\d+/ do
      member do
        get 'upvote'
        get 'downvote'
        get 'debug'
        resources :comments
      end
      collection do
        post 'fetch'
        get 'recommendations'
      end
    end
  end

  devise_scope :user do
    root :to => 'home#index'
    get '/about' => 'home#about'
    match '/404', :to => 'errors#error_404'
    match '/500', :to => 'errors#error_500'
  end

end

app/controllers/home_controller.rb
class HomeController < Devise::SessionsController
  # before_filter :authenticate_user!, :only => :index
  prepend_before_filter :require_no_authentication, :only => [ :new, :create ]
  prepend_before_filter :allow_params_authentication!, :only => :create
  prepend_before_filter { request.env["devise.skip_timeout"] = true }
  layout "splash", :except => :index

  def index
    # TODO: Why doesn't the before filter work?
    redirect_to new_user_session_path if !current_user.present?
  end

  # GET /resource/sign_in
  def new
    self.resource = build_resource(nil, :unsafe => true)
    clean_up_passwords(resource)
    respond_with(resource, serialize_options(resource))
  end

  # POST /resource/sign_in
  def create
    self.resource = warden.authenticate!(auth_options)
    set_flash_message(:notice, :signed_in) if is_navigational_format?
    sign_in(resource_name, resource)
    respond_with resource, :location => after_sign_in_path_for(resource)
  end

  # DELETE /resource/sign_out
  def destroy
    redirect_path = after_sign_out_path_for(resource_name)
    signed_out = (Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name))
    set_flash_message :notice, :signed_out if signed_out && is_navigational_format?

    # We actually need to hardcode this as Rails default responder doesn't
    # support returning empty response on GET request
    respond_to do |format|
      format.all { head :no_content }
      format.any(*navigational_formats) { redirect_to redirect_path }
    end
  end

  protected

  def serialize_options(resource)
    methods = resource_class.authentication_keys.dup
    methods = methods.keys if methods.is_a?(Hash)
    methods << :password if resource.respond_to?(:password)
    { :methods => methods, :only => [:password] }
  end

  def auth_options
    { :scope => resource_name, :recall => "#{controller_path}#new" }
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_article_links.html.haml
%ul.article-links
  %li
    = link_to upvote_post_path(article), :remote => 'true', :class => (@votes.detect { |v| v.post_id == article.id && v.direction == Vote.UP }.present? ? 'voted' : '') do
      %i.icon-plus
  %li
    = link_to downvote_post_path(article), :remote => 'true', :class => (@votes.detect { |v| v.post_id == article.id && v.direction == Vote.DOWN }.present? ? 'voted' : '') do
      %i.icon-minus
  - if article.comments.length > 1
    %li= link_to "#{article.comments.length} comments", post_path(article)
  - elsif article.comments.length == 1
    %li= link_to "1 comment", post_path(article)
  - else
    %li= link_to "comment", post_path(article)
  .avatar-group-small
    - article.commenters.limit(5).each do |c|
      = image_tag gravatar_url(c, 12), :class => 'avatar-image-small'

app/views/home/_debug.html.haml
.recommended-because
  = link_to debug_post_path(article) do
    %i.icon-question-sign
      .reason
        Weight: #{article.try(:weight).try(:round, 2) || "(unknown)"}

app/views/home/_feature_article.html.haml
.article.featured.primary{ :style => "background-image: url(#{article.image.url})" }
  = render 'home/debug', :article => article if current_user.debug_user?
  %h2
    =link_to article.title, article.url
  = render 'home/posted_by', :article => article
  = render 'home/article_links', :article => article

app/views/home/_onboard.html.haml
.article.box{ :style => ' width: 63%; height: 400px;' }
  %h2{ :style => 'text-align: center;margin-bottom: 20px;' } Welcome to October!
  %p
    %b Hmm, it looks like we don't know each other.
  %p
    You're looking at some of the newest content submitted to October. We want to
    %b customize
    it to your liking, so would you please give us a couple keywords you'd like to follow?
  = form_for('onboard', :url => keywords_path(current_user)) do |f|
    %ul#onboard_terms
    %span.help-block separate keywords with commas
    = f.submit 'Customize!', :class => 'btn btn-primary'

app/views/home/_posted_by.html.haml
.posted_by
  - if article.poster.is_a?(Feed)
    from
    = link_to article.poster.name, feed_path(article.poster_id)
  - elsif article.poster.is_a?(User)
    by
    = link_to article.poster.name, user_path(article.poster.name)
    = image_tag gravatar_url(article.poster, 20), :class => 'avatar-image-small'
  &middot; posted
  = distance_of_time_in_words(article.created_at, Time.now)
  ago

app/views/home/_square_article_primary.html.haml
.article.square.box.primary
  = render 'home/debug', :article => article if current_user.debug_user?
  %h2
    =link_to article.title, article.url
  = render 'home/posted_by', :article => article
  = render 'home/article_links', :article => article

app/views/home/_square_article_primary_picture.html.haml
.article.square.with-picture.box.primary
  = render 'home/debug', :article => article if current_user.debug_user?
  = image_tag article.image.url(:square), :data => { :ratio => article.image_height_as_pct }, :class => 'article-image'
  %h2
    = link_to article.title, article.url
  = render 'home/posted_by', :article => article
  = render 'home/article_links', :article => article

app/views/home/_square_article_secondary.html.haml
.article.square.notbox.secondary
  = render 'home/debug', :article => article if current_user.debug_user?
  .title
    %h2
      =link_to article.title, article.url
  = render 'home/posted_by', :article => article
  = render 'home/article_links', :article => article

app/views/home/_square_article_secondary_picture.html.haml
.article.square.with-picture.notbox.secondary
  = render 'home/debug', :article => article if current_user.debug_user?
  = image_tag article.image.url(:square), :data => { :ratio => article.image_height_as_pct }, :class => 'img-secondary article-image'
  .title
    %h2
      = link_to article.title, article.url
  = render 'home/posted_by', :article => article
  = render 'home/article_links', :article => article

app/views/home/about.html.haml
.span11
  %h3 What is October?
  %p
    October is a news aggregation website, where all the cool, interesting
    articles and bits of information from around the web coalesce and are served
    up fresh for your perusing pleasure! October uses your viewing preferences
    to filter through articles and pick out the ones that are most pertinent to
    you, providing you with a seamless browsing experience where
    %em everything
    on the front page is worth your time.
  %h3 How did October come to be?
  %p
    We here at October had a dream, a dream that involved a place where one
    wouldn’t need to endlessly scroll through the depths of the internet to find
    the bits that were really worthwhile. October is an attempt to make those
    dreams into a reality, and also as a class project for our senior year at
    Case Western Reserve University (But mostly the former, because it’s
    sexier).
  %h3 Why is it called October?
  %p
    By using a recommendation engine, we believe this community will be able to
    tolerate large influxes of new users with no decrease in the quality of discourse, thus
    breaking through the #{link_to 'Eternal September', 'http://en.wikipedia.org/wiki/Eternal_September'} phenomenon.
  %h3 Who are the people who made this wonderful place?
  %p
    October was created by Brian, Tom and Mika: three intrepid and daring (and
    dashing) seniors at Case Western Reserve University in lovely Cleveland, OH.
  %p
    =image_tag 'brian.jpg', :style => 'width: 64px;'
    %p
      Brian, when not creating the guts of the website that you are currently
      enjoying, spends his leisure time solving stuff like P=NP and whether or not
      3SUM can be solved in subquadratic time.
  %p
    =image_tag 'tom.jpg', :style => 'width: 64px;'
    %p
      Tom recently returned from Botswana where he rescued 26 children from a
      float of crocodiles when they attacked a small shore-side village (the crocodiles, not the children). No
      lizards were hurt in the process.
  %p
    =image_tag 'mika.jpg', :style => 'width: 64px;'
    %p
      Mika just beat God of War: Ascension on Titan difficulty and realized that
      there is, in fact, no PS3 trophy for doing so and now feels swindled.

app/views/home/index.html.haml
-content_for :stylesheets do
  = stylesheet_link_tag 'home'
-content_for :javascripts do
  = javascript_include_tag 'home'
  :javascript
    $(function() {
      OctoberHomepage.init("#{params[:search] && params[:search][:query] ? params[:search][:query] : ""}");
      #{"mixpanel.track(\"Search\", { query: \"#{params[:search][:query]}\", });" if params[:search]}
    });
- if current_user.needs_onboarding?
  - content_for :javascripts do
    = javascript_include_tag 'tag-it.min'
  - content_for :stylesheets do
    = stylesheet_link_tag 'tag-it'
.row#articles
  =image_tag 'loading.gif', :style => 'width: 14px; float: left; margin-right: 10px; margin-top: 3px;'
  %p Please wait, we'll have your recommendations in just a moment...