config/routes.rb
ProjectOctober::Application.routes.draw do

  devise_for :users, :path => 'auth', :controllers => {
    :registrations => 'users',
    :sessions => 'home',
  }
  devise_scope :user do
    resources :users, :only => :show do
      resources :subscriptions, :only => [:create, :destroy]

      member do
        get 'follow'
        get 'unfollow'
        get 'keywords'
        resource :keywords, :only => [:create, :destroy], :controller => 'user_keywords'
      end
    end

    resources :feeds, :only => :show, :controller => 'users' do
      member do
        get 'follow'
        get 'unfollow'
      end
    end

    resources :posts, :id => /\d+/ do
      member do
        get 'upvote'
        get 'downvote'
        get 'debug'
        resources :comments
      end
      collection do
        post 'fetch'
        get 'recommendations'
      end
    end
  end

  devise_scope :user do
    root :to => 'home#index'
    get '/about' => 'home#about'
    match '/404', :to => 'errors#error_404'
    match '/500', :to => 'errors#error_500'
  end

end

app/models/post.rb
# encoding: utf-8

class Post < ActiveRecord::Base
  attr_accessor :keywords, :images      # Only populated in Post.new_from_url()
  attr_accessor :weight                 # Only populated in Post.assign_types()
  attr_accessible :title, :url, :keywords, :images
  has_attached_file :image, :styles => {
    :featured => "749x400",
    :square => '363'
  }

  has_many :comments
  has_many :commenters, :through => :comments, :source => :user, :order => 'created_at DESC', :uniq => true
  has_many :votes
  belongs_to :poster

  before_save :set_image_if_necessary

  validates_presence_of :poster_id
  validates_presence_of :title

  validates_uniqueness_of :title, :scope => :poster_id
  validates_uniqueness_of :url, :scope => :poster_id

  def image_height_as_pct
    return 0 unless image.present?
    width, height = image.image_size.split('x').map(&:to_f)
    height / width
  end

  # Class methods (i.e. Post.recommendations_for(user, n) )
  class << self
    def recommendations_for(user, n=30)
      posts = THRIFTCLIENT.recPosts(user.id, n, 0).posts.inject({}) { |a,i| a.merge(i.post_id => i.weight) }
      if posts.empty?
        return Post.order('created_at DESC').first(n).map do |p|
          [p, p.image.present? ? :square_article_primary_picture : :square_article_primary]
        end
      end

      assign_types(posts)
    end

    # Takes a hash of { post_id => weight } and assigns display types for them.
    def assign_types(post_list)
      num_primary = (0.5 * post_list.length).round

      posts = Post.
        find(post_list.keys, :include => [:poster, :comments]).
        each { |p| p.weight = post_list[p.id] }.
        sort_by { |p| p.weight }.
        reverse

      # Frontpage display algorithm:
      # 1) Find the highest weighted story that is eligible to be a featured
      #    post. It is the featured post.
      # 2) All other articles are to be displayed with an image if possible in
      #    order according to weight.
      featured = posts.detect { |p| p.image.present? }
      posts = posts - [featured]
      other_featured = posts.detect { |p| p.image.present? }
      posts = posts - [other_featured]

      post_type_list = posts.map do |p|
        primary = (num_primary -= 1) > 0 ? :primary : :secondary
        type = if p.image.present?
          "square_article_#{primary}_picture"
               else
          "square_article_#{primary}"
               end.to_sym

        [ p, type ]
      end

      # Pseudo-shuffle here:
      post_type_list = post_type_list.group_by { |p, _| p.id % 4 }.values.flatten(1)

      # Add the featured articles back in:
      post_type_list.unshift([featured, :feature_article]) if featured.present?
      post_type_list.insert(post_type_list.length / 4, [other_featured, :feature_article]) if other_featured.present?

      post_type_list
    end

    def new_from_url(url)
      images, title, leader, keywords = fetch_from_url(url)

      oct_vec = keywords.map do |pair|
        Backend::Token.new(:t => pair[0], :f => pair[1])
      end

      Post.new(
        :title     => title,
        :url       => url,
        :keywords  => oct_vec,
        :images    => images,
      )
    end

    def fetch_from_url(url)
      post = Pismo::Document.new(url, :reader => :cluster)
      images = post.images || []
      leader = post.lede # This is the first couple sentences.
      keywords = post.keywords(
        :limit => 50
      ).delete_if { |keyword, occur| keyword.to_i != 0 }

      return [
        post.images || [],
        post.title,
        post.lede,
        keywords
      ]
    end
  end

private

  def set_image_if_necessary
    if image.blank? && images.present?
      images.each do |url|
        self.image = URI.parse(url)
        self.image.destroy if self.image.width < 200 || self.image.height < 50
      end
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!, :only => [:debug, :recommendations]
  before_filter :ensure_debug!, :only => :debug

  def show
    @post = Post.find(params[:id])
  end

  def new

  end

  def debug
    @post = Post.find(params[:id])
    @post = Post.new_from_url(@post.url)
  end

  def recommendations
    if params[:search][:query].present?
      @query = params[:search][:query]
      results = THRIFTCLIENT.textSearch(@query.split(' '), 50, 0)
      @posts = Post.assign_types(results)
    else
      @posts = Post.recommendations_for(current_user)
    end

    @votes = current_user.votes.where(:post_id => @posts.map(&:first))

    render :layout => nil
  end

  def fetch
    return unless request.xhr?
    begin
      @post = Post.new_from_url(params[:url])
    rescue
      return render :json => { :error => 'Could not fetch!' }
    end
    return render :json => {
      :images => @post.images,
      :title => @post.title,
      :keywords => @post.keywords.map(&:t),
    }
  end

  def create
    begin
      @post = Post.new_from_url(params[:post][:url])
      @post.title = params[:post][:title] if params[:post][:title].present?
      @post.image = open(params[:post][:image_url]) if params[:post][:image_url].present?
      @post.keywords = params[:post][:keywords] if params[:post][:keywords].present?
      @post.poster = current_user
    rescue
      return redirect_to new_post_path, :flash => {
        :error => "Could not fetch article!"
      }
    end

    if @post.keywords.empty?
      return redirect_to new_post_path, :flash => {
        :error => "Could not determine article keywords!"
      }
    end

    if @post.title.blank?
      return redirect_to new_post_path, :flash => {
        :error => "Could not determine article title!"
      }
    end

    if @post.save
      # TODO: Save the post to the db to get the second param and get the first from the current user
      if THRIFTCLIENT.addPost(current_user.id, @post.id, @post.keywords)
        redirect_to root_path, :flash => {
          :notice => "Success! Your article has been submitted."
        }
      else
        redirect_to new_post_path, :flash => { :error => "Could not add article to backend database!" }
      end
    else
      redirect_to new_post_path, :flash => { :error => "Could not add article to frontend database!" }
    end
  end

  def upvote
    @post = Post.find(params[:id])
    render :text => current_user.vote(@post, Vote.UP)
  end

  def downvote
    @post = Post.find(params[:id])
    render :text => current_user.vote(@post, Vote.DOWN)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def recursify_array_of_comments(comments, parent_id = nil)
    # Takes an array of comments and returns a hash that looks like:
    # [
    #   {
    #   :root => #<Comment 1>
    #   :children => [
    #     {
    #       :root => #<Comment 2>,
    #       :children => [...]
    #     }, ...
    #   ]},
    #   {
    #     :root => #<Comment 3>,
    #   ...and so forth...
    roots = comments.find_all { |c| c.parent_id == parent_id }
    roots.map { |c| { :root => c, :children => recursify_array_of_comments(comments, c.id) } }
  end
end

app/views/posts/_comment_list.html.haml
- comment = comment_list[:root]
.comment
  = image_tag gravatar_url(comment.user, 12), :class => 'avatar-image-small'
  #{comment.user.name} - #{distance_of_time_in_words(comment.created_at, Time.now)} ago
  %p= comment.body
  = render 'new_comment', :parent_id => comment.id, :post_id => comment.post_id
  - comment_list[:children].each do |comment_and_child_comments|
    = render 'comment_list', :comment_list => comment_and_child_comments

app/views/posts/_new_comment.html.haml
= form_for(Comment.new(:post_id => post_id, :parent_id => parent_id)) do |f|
  = f.hidden_field :post_id
  = f.hidden_field :parent_id
  .comment-reply-area
    .comment
      #{current_user.name} - [draft]
      %p= f.text_area :body, :class => 'span6', :style => 'height: 100px;'
      = f.submit 'Post Comment', :class => 'btn'
  .clearfix
    - if parent_id.nil?
      =link_to 'Post New Comment', '#', :class => 'btn comment-reply-btn'
    - else
      = link_to 'Reply', '#', :class => 'comment-reply-btn'

app/views/posts/debug.html.haml
%h2= @post.title
%p= link_to @post.url, @post.url
.clearfix
  %h3 Images
  - @post.images.each do |img|
    = image_tag img, :style => 'float: left;'
.clearfix
  %h3 Keywords
  %ul
    - @post.keywords.each do |token|
      %li
        %p
          %b=token.t
          (#{token.f})

app/views/posts/new.html.haml
- content_for :javascripts do
  :javascript
    var OctoberSubmitPage = (function($) {
      var $form = $("#new_post");
      var $urlField = $form.find("#post_url");
      var $imageUrlField = $form.find("#post_image_url");
      var $titleField = $form.find("#post_title");
      var $imagesArea = $form.find("#form-image-group");
      var $keywordsArea = $form.find("#form-keywords-group");
      var $loadingGif = $form.find(".loading-gif");
      var fetchUrl = "#{fetch_posts_path}";

      var init = function() {
        $urlField.on('change', urlChangeHandler);
        hideSections();
        resetSections();

        mixpanel.track_forms("#new_post", "Submitted Post");
      };

      var hideSections = function() {
        $imagesArea.hide();
        $keywordsArea.hide();
        $loadingGif.hide();
      };

      var resetSections = function() {
        $titleField.val("");
        $imagesArea.find(".controls").html('');
        $keywordsArea.find(".controls").html('<ul></ul>');
      };

      var urlChangeHandler = function(e) {
        if (this.value === "") {
          resetSections();
        }
        $titleField.attr('placeholder', 'Please wait, fetching...');
        $loadingGif.show();
        $.post(fetchUrl, { url: this.value }, postFetchedHandler, 'json');
      };

      var selectImage = function($img) {
        $img.parent().children().removeClass('selected');
        $imageUrlField.val($img.data('image-url'));
        $img.addClass('selected');
      };

      var selectImageHandler = function(ev) {
        selectImage($(ev.target));
        return false;
      };

      var postFetchedHandler = function(data) {
        if (data.error) {
          resetSections();
          hideSections();
        }

        // Done loading, hide the loading animation
        $loadingGif.hide();
        $titleField.attr('placeholder', '');

        // Populate the images
        $imageControlsArea = $imagesArea.find(".controls");
        $.each(data.images, function(index, url) {
          $imageControlsArea.append("<div data-image-url=\"" + url + "\" style=\"background: url('" + url + "'); background-size: cover;\" class=\"article-image\"></div>");
        });
        selectImage($imageControlsArea.find(":first"));
        $imageControlsArea.on('click', selectImageHandler);
        $imagesArea.show();

        // Populate the title
        $titleField.val(data.title);

        // Populate the keywords
        $keywordListArea = $keywordsArea.find(".controls ul");
        $.each(data.keywords, function(index, keyword) {
          if (index >= 5) { return false; }
          $keywordListArea.append("<li>" + keyword + "</li>");
        });
        $keywordListArea.tagit({ fieldName: 'keywords[]', allowSpaces: true });
        $keywordsArea.show();
      };

      return { init : init };
    }($));

    $(function() {
      OctoberSubmitPage.init();
    });
- content_for :javascripts do
  = javascript_include_tag 'tag-it.min'
- content_for :stylesheets do
  = stylesheet_link_tag 'posts'
  = stylesheet_link_tag 'tag-it'
.span8
  %h2 Post A New Article
  = form_for(Post.new, :method => :post, :html => { :class => 'form-horizontal' }) do |f|
    .control-group
      .control-label
        =f.label :url
      .controls
        =f.text_field :url, :class => 'span6'
    .control-group#form-image-group
      .control-label
        =f.label :images
        %span.help-block select one
        =hidden_field_tag 'post[image_url]'
      .controls
    .control-group#form-keywords-group
      .control-label
        =f.label :keywords
        %span.help-block separate keywords with commas
      .controls
    .control-group
      .control-label
        =f.label :title
      .controls
        =f.text_field :title, :class => 'span6'
        =image_tag 'loading.gif', :class => 'loading-gif'
    .form-actions
      =f.submit 'Post Article!', :class => 'btn btn-primary'

app/views/posts/recommendations.html.haml
- if current_user.needs_onboarding? && !@query
  = render "home/onboard"
- if @posts.empty?
  .article
    %p Couldn't find any posts!
- else
  - @posts.each do |p|
    = render "home/#{p[1]}", :article => p[0]

app/views/posts/show.html.haml
- content_for :stylesheets do
  = stylesheet_link_tag 'posts'
- content_for :javascripts do
  :javascript
    $(function() {
      $(".comment-reply-area").hide();
      $(".comments").on('click', function(ev) {
        $target = $(ev.target);
        if ($target.is(".comment-reply-btn")) {
          $target.hide();
          $commentReplyArea = $target.parent().siblings().filter(".comment-reply-area");
          $commentReplyArea.show();
          $commentReplyArea.find("textarea").focus();
        }
      });
    });
%h2= link_to @post.title, @post.url
.posted_by
  - if @post.poster.is_a?(Feed)
    Posted from
    = link_to @post.poster.name, feed_path(@post.poster_id)
  - elsif @post.poster.is_a?(User)
    Posted by
    = link_to @post.poster.name, user_path(@post.poster.name)
    = image_tag gravatar_url(@post.poster, 20), :class => 'avatar-image-small'
  &middot;
  = distance_of_time_in_words(@post.created_at, Time.now)
  ago
%h3 Comments:
.comments
  - @comments = recursify_array_of_comments(@post.comments)
  - @comments.each do |comment_and_child_comments|
    = render 'comment_list', :comment_list => comment_and_child_comments
  = render 'new_comment', :parent_id => nil, :post_id => @post.id