config/routes.rb
ProjectOctober::Application.routes.draw do

  devise_for :users, :path => 'auth', :controllers => {
    :registrations => 'users',
    :sessions => 'home',
  }
  devise_scope :user do
    resources :users, :only => :show do
      resources :subscriptions, :only => [:create, :destroy]

      member do
        get 'follow'
        get 'unfollow'
        get 'keywords'
        resource :keywords, :only => [:create, :destroy], :controller => 'user_keywords'
      end
    end

    resources :feeds, :only => :show, :controller => 'users' do
      member do
        get 'follow'
        get 'unfollow'
      end
    end

    resources :posts, :id => /\d+/ do
      member do
        get 'upvote'
        get 'downvote'
        get 'debug'
        resources :comments
      end
      collection do
        post 'fetch'
        get 'recommendations'
      end
    end
  end

  devise_scope :user do
    root :to => 'home#index'
    get '/about' => 'home#about'
    match '/404', :to => 'errors#error_404'
    match '/500', :to => 'errors#error_500'
  end

end

app/views/layouts/_global_header.html.haml
%meta{ :name => 'viewport', :content => 'width=device-width, initial-scale=1.0' }
%meta{ :name => 'description', :content => "October helps you read the news you want to read. We will recommend news stories that you'll find interesting based on text analysis and what kinds of news you have told us that you enjoy." }
%meta{ :'http-equiv' => 'Content-Type', :content => 'text/html', :charset => 'utf8' }
= stylesheet_link_tag    "application", :media => "all"
= yield :stylesheets
/ Intentionally block page load to get the fonts
= javascript_include_tag '//use.typekit.net/vxb6zze.js'
:javascript
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-39936366-1', 'case.edu');
  ga('send', 'pageview');

  (function(e,b){if(!b.__SV){var a,f,i,g;window.mixpanel=b;a=e.createElement("script");a.type="text/javascript";a.async=!0;a.src=("https:"===e.location.protocol?"https:":"http:")+'//cdn.mxpnl.com/libs/mixpanel-2.2.min.js';f=e.getElementsByTagName("script")[0];f.parentNode.insertBefore(a,f);b._i=[];b.init=function(a,e,d){function f(b,h){var a=h.split(".");2==a.length&&(b=b[a[0]],h=a[1]);b[h]=function(){b.push([h].concat(Array.prototype.slice.call(arguments,0)))}}var c=b;"undefined"!==
  typeof d?c=b[d]=[]:d="mixpanel";c.people=c.people||[];c.toString=function(b){var a="mixpanel";"mixpanel"!==d&&(a+="."+d);b||(a+=" (stub)");return a};c.people.toString=function(){return c.toString(1)+".people (stub)"};i="disable track track_pageview track_links track_forms register register_once alias unregister identify name_tag set_config people.set people.set_once people.increment people.append people.track_charge people.clear_charges people.delete_user".split(" ");for(g=0;g<i.length;g++)f(c,i[g]);
  b._i.push([a,e,d])};b.__SV=1.2}})(document,window.mixpanel||[]);
  mixpanel.init("#{Rails.env == 'production' && 'c6a718bb5247d260903d4ce61a27ac67'}");
  #{"mixpanel.identify(\"#{current_user.email}\");" if current_user.present?}
  #{"mixpanel.name_tag(\"#{current_user.name}\");" if current_user.present?}
  mixpanel.track("Page View", {
    page: window.location.pathname,
  });

  try{Typekit.load();}catch(e){}
= csrf_meta_tags

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Project October
    = render 'layouts/global_header'
  %body
    - if THRIFTCLIENT.read_only_mode?
      .read-only-mode
        %p We're experiencing some troubles at the moment. October is temporarily in amnesia mode.
    .container#logobar
      .row
        .span4
          %h1.logo= link_to 'October', root_path
        .span8
          .right-nav-items.btn-group
            = link_to 'Logout', destroy_user_session_path, :class => 'btn', :method => 'delete', :style => 'float: right'
            = link_to current_user.name, user_path(current_user.name), :class => 'btn', :style => 'float: right'
            = link_to 'Post an Article', new_post_path, :class => 'btn hidden-phone', :style => 'float: right'
            = link_to 'Search', '#', :class => 'hidden-desktop btn', :id => 'tablet-search-button'
            = form_for('search', :url => root_path, :html => { :style => 'float: right;', :class => 'visible-desktop'}) do |f|
              =f.text_field :query, :placeholder => "Search for user, keyword, or feed", :class => 'span4'
      .row#tablet-search-row
        .span12
          = form_for('search', :url => root_path) do |f|
            =f.text_field :query, :placeholder => "Search for user, keyword, or feed"
      - if flash[:notice] || flash[:error]
        #alert-bar
          - if flash[:notice]
            .alert.alert-info= flash[:notice]
          - if flash[:error]
            .alert.alert-error= flash[:error]
      - if @query.present?
        .row
          .span12
            %h2 Showing results for "#{@query}":
        - if @user_results.present?
          .row
            .span12
              %h3 Users
              %ol.user-results
                - @user_results.each do |u|
                  %li.box
                    %h3
                      #{image_tag gravatar_url(u, 32)}
                      = link_to u.name, user_path(u.name)
    .container#articles
      = yield
    = javascript_include_tag "application"
    = yield :javascripts

app/views/layouts/email.html.haml
= stylesheet_link_tag 'email'
%h1.logo October
= yield
%p#footer
  This email was sent automatically by Project October. To unsubscribe from
  emails... just kidding, there is no way to unsubscribe from emails yet.

app/views/layouts/splash.html.haml
!!! 5
%html
  %head
    %title Project October
    = render 'layouts/global_header'
    :css
      body, html {
        height: 100%;
        background: url(#{image_path('splash_background.jpg')}) top left no-repeat;
        background-size: cover;
      }
      #splash {
        background-color: rgba(255, 255, 255, 0.5);
        padding: 5px 0 30px;
        margin-top: 50px;
        box-shadow: 0px 0px 5px rgba(0, 0, 0, 0.3)
      }
      .logo a { color: #555; }
      .logo {
        display: inline-block;
        background: none;
        padding-left: 0;
      }
      #errorbar {
        font-family: 'museo sans', Helvetica, sans-serif;
        text-align: center;
        background-color: #ff8930;
        padding-top: 10px;
        margin-bottom: 20px;
      }
      #footer {
        margin-top: 20px;
        font-size: 1.2em;
        color: #ddd;
      }
      #footer ul {
        list-style: none;
        margin: 0 0 0 30px;
      }
      #footer li {
        float: left;
      }
      #footer li:before {
        content: "\00b7";
        margin: 0 10px;
        display: inline-block;
      }
      #footer li:first-child:before {
        display: none;
        content: '';
      }
      #footer a {
        color: #ddd;
      }
      @media (max-width: 767px) {
        #splash {
          padding-left: 20px;
          padding-right: 20px;
        }
      }
  %body
    .container
      #splash
        .row#logobar
          .span4
            %h1.logo= link_to 'October', root_path, :style => 'margin: auto;'
        - if flash[:error] || flash[:alert]
          .row
            .span12#errorbar
              %p #{flash[:error] || flash[:alert]}
        .row
          .span12
            =yield
      #footer
        %ul
          %li
            October is a project for EECS395 at Case Western Reserve University
          %li= link_to 'About Us', about_path
    = javascript_include_tag 'application'
    = yield :javascripts